# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_project_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(verbose_name=b'Accept\xc3\xa9')),
                ('amount', models.PositiveIntegerField(verbose_name=b'Montant')),
            ],
            options={
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submission', models.DateTimeField(verbose_name=b'Date de soumission')),
            ],
            options={
                'verbose_name_plural': 'Voix',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name=b"Date d'ouverture")),
                ('end_date', models.DateTimeField(verbose_name=b'Date de fermeture')),
                ('amount', models.PositiveIntegerField(verbose_name=b'Budget')),
                ('projects', models.ManyToManyField(related_name='Votes', to='project.Project', verbose_name=b'Projects')),
                ('users', models.ManyToManyField(related_name='Votes', to=settings.AUTH_USER_MODEL, verbose_name=b'Users')),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Voix', to='vote.Vote', verbose_name=b'Vote'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choix', to='vote.Poll', verbose_name=b'Voix'),
        ),
        migrations.AddField(
            model_name='choice',
            name='sub_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choix', to='project.SubProject', verbose_name=b'Sous-projet'),
        ),
    ]
