language: python


python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* manage.py test
  - pep8 --count --show-source --exclude=migrations,plateforme_budgetaire,locale,static,templates ./plateforme_budgetaire/

after_success:
  coveralls