language: python

python:
  - 3.5

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* plateforme_budgetaire/manage.py test plateforme_budgetaire/
  - pep8 --count --show-source --exclude=migrations,plateforme_budgetaire/plateforme_budgetaire,manage.py plateforme_budgetaire/

after_success:
  coveralls