# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nom')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('number_affected_by', models.PositiveIntegerField(verbose_name=b'Nombre de personne affect\xc3\xa9es')),
                ('justification', models.TextField(verbose_name=b'Justification')),
                ('completion_time', models.DurationField(verbose_name=b'Temps de r\xc3\xa9alisation')),
                ('date_of_submission', models.DateTimeField(verbose_name=b'Date de soumission')),
                ('author_name', models.CharField(max_length=100, verbose_name=b'Nom')),
                ('author_website', models.TextField(verbose_name=b'Site web')),
                ('author_description', models.TextField(verbose_name=b'Description')),
                ('status', models.CharField(choices=[(b'In waiting', 0), (b'Accepted', 1), (b'Rejected', 2)], max_length=100, verbose_name=b'Valid\xc3\xa9')),
            ],
            options={
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nom')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('completion_time', models.DurationField(verbose_name=b'Temps de r\xc3\xa9alisation')),
                ('minimum_amount', models.PositiveIntegerField(verbose_name=b'Montant minimal')),
                ('maximum_amount', models.PositiveIntegerField(verbose_name=b'Montant maximal')),
            ],
            options={
                'verbose_name_plural': 'Sous-Projets',
            },
        ),
    ]
