# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(verbose_name=b'hash')),
                ('duration', models.DurationField(verbose_name=b'Temps de vie')),
                ('action', models.TextField(verbose_name=b'Action authoris\xc3\xa9')),
                ('created', models.DateTimeField(verbose_name=b'Date of creation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hashs', to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'verbose_name_plural': 'Hashs',
            },
        ),
    ]
