# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='used',
            field=models.BooleanField(default=False, verbose_name=b'Utilis\xc3\xa9'),
        ),
    ]
